#!/usr/bin/env node
/*
 * Builds the static site for GitHub Pages or any other static host.
 *
 * The app needs no compilation, so the build copies app/ as it is and only:
 *   - stamps the version (commit) into js/version.js, shown in the help;
 *   - appends ?v=<version> to every module import and to the stylesheet,
 *     script and icon in index.html, so a new deployment is never mixed with
 *     files of the previous one still in a browser cache (GitHub Pages lets
 *     browsers cache everything for 10 minutes);
 *   - fails when an import or an asset does not resolve - with the exact
 *     upper/lower case, as web servers are case-sensitive.
 *
 * Usage: node scripts/build-site.mjs [outDir]   (default: _site)
 */
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const src = path.join(root, 'app');
const out = path.resolve(process.argv[2] || path.join(root, '_site'));

function git(...args) {
  try {
    return execFileSync('git', args, { cwd: root, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim();
  } catch {
    return '';
  }
}

const version = (process.env.GITHUB_SHA || git('rev-parse', 'HEAD') || 'dev').slice(0, 7);
const date = (git('log', '-1', '--format=%cI') || new Date().toISOString()).slice(0, 10);
const errors = [];

/** True when the path exists with exactly this spelling, segment by segment. */
function existsExact(file) {
  const rel = path.relative(out, file);
  if (rel.startsWith('..') || path.isAbsolute(rel)) return false;
  let dir = out;
  for (const part of rel.split(path.sep)) {
    if (!fs.existsSync(dir) || !fs.readdirSync(dir).includes(part)) return false;
    dir = path.join(dir, part);
  }
  return true;
}

function walk(dir, ext, list = []) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walk(p, ext, list);
    else if (p.endsWith(ext)) list.push(p);
  }
  return list;
}

// 1. fresh copy of the app
if (out === root || out === src || src.startsWith(out + path.sep)) throw new Error(`refusing to build into ${out}`);
fs.rmSync(out, { recursive: true, force: true });
fs.cpSync(src, out, { recursive: true });

// 2. version stamp
fs.writeFileSync(
  path.join(out, 'js', 'version.js'),
  `/* Generated by scripts/build-site.mjs. */\nexport const BUILD = { version: ${JSON.stringify(version)}, date: ${JSON.stringify(date)} };\n`,
);

// 3. versioned module imports (every import of a file must carry the same URL, or the module would load twice)
const IMPORT_RE = /(\bfrom\s*|\bimport\s*\(?\s*)(['"])(\.{1,2}\/[^'"]+)\2/g;
let imports = 0;
for (const file of walk(path.join(out, 'js'), '.js')) {
  const code = fs.readFileSync(file, 'utf8');
  const next = code.replace(IMPORT_RE, (m, pre, q, spec) => {
    const target = path.resolve(path.dirname(file), spec);
    if (!existsExact(target)) errors.push(`${path.relative(out, file)}: import '${spec}' does not resolve`);
    imports++;
    return `${pre}${q}${spec}?v=${version}${q}`;
  });
  if (/\bfrom\s*['"]\.{1,2}\/[^'"?]+['"]/.test(next)) errors.push(`${path.relative(out, file)}: unversioned import left`);
  fs.writeFileSync(file, next);
}

// 4. index.html: versioned local assets
const indexFile = path.join(out, 'index.html');
let html = fs.readFileSync(indexFile, 'utf8');
let assets = 0;
html = html.replace(/\b(src|href)="([^"#:]+)"/g, (m, attr, url) => {
  if (url.startsWith('//')) return m;
  if (!existsExact(path.resolve(out, url))) errors.push(`index.html: ${attr}="${url}" does not resolve`);
  assets++;
  return `${attr}="${url}?v=${version}"`;
});
if (!html.includes('http-equiv="Content-Security-Policy"')) errors.push('index.html: the Content-Security-Policy meta tag is missing');
fs.writeFileSync(indexFile, html);

if (errors.length) {
  console.error(`Build failed:\n  ${errors.join('\n  ')}`);
  process.exit(1);
}
const files = walk(out, '');
const bytes = files.reduce((s, f) => s + fs.statSync(f).size, 0);
console.log(`Built ${path.relative(root, out) || out}: version ${version} (${date}), ${files.length} files, ${(bytes / 1024).toFixed(0)} KiB, ${imports} imports and ${assets} assets versioned.`);
